export const vars = {
  colors: {
    light: {
      background: "#fdfdfd",
      foreground: "#000000",
      card: "#fdfdfd",
      card_foreground: "#000000",
      popover: "#fcfcfc",
      popover_foreground: "#000000",
      primary: "#7033ff",
      primary_foreground: "#ffffff",
      secondary: "#edf0f4",
      secondary_foreground: "#080808",
      muted: "#f5f5f5",
      muted_foreground: "#525252",
      accent: "#e2ebff",
      accent_foreground: "#1e69dc",
      destructive: "#e54b4f",
      destructive_foreground: "#ffffff",
      border: "#e7e7ee",
      input: "#ebebeb",
      ring: "#000000",
      placeholder: "#a3a2a2",
      success: "#22c55e",
      success_foreground: "#ffffff",
    },
    dark: {
      background: "#fdfdfd",
      foreground: "#000000",
      card: "#fdfdfd",
      card_foreground: "#000000",
      popover: "#fcfcfc",
      popover_foreground: "#000000",
      primary: "#7033ff",
      primary_foreground: "#ffffff",
      secondary: "#edf0f4",
      secondary_foreground: "#080808",
      muted: "#f5f5f5",
      muted_foreground: "#525252",
      accent: "#e2ebff",
      accent_foreground: "#1e69dc",
      destructive: "#e54b4f",
      destructive_foreground: "#ffffff",
      border: "#e7e7ee",
      input: "#ebebeb",
      ring: "#000000",
      placeholder: "#525252",
      success: "#22c55e",
      success_foreground: "#ffffff",
    },
  },
} as const;
